### ISSUE TITLE
Color Fading hangs ?

### ISSUE THREAD

**Issue by kohaistyle** [okcoker/jquery-airport#1]
Great plugin ! Works almost as it should, except the color cycling  sometimes stalls ?
Fade to the first color of the list, and then stays there. Any ideas ?

Seen there : www.kohai.net

**Comment by okcoker** [comment]
Hey can you try the updated version and see if that fixes your problem?

**Comment by kohaistyle** [comment]
Fixed ... Works a treat ! You rock ;)
